version: '3'
services:
  clipfinder:
    build: ./clipfinder
    command: 'go test -v ./...'
  clipstitcher:
    build: ./clipstitcher
    command: 'go test -v ./...'
  archiver:
    build: ./archiver
    command: bash -c 'mocha'
  aggregator:
    build: './aggregator'
    command: bash -c 'mocha'