version: '3'
services:
  clipstitcher:
    build: ./clipstitcher
    volumes:
      - ./clipstitcher:/go/src/github.com/user/clipstitcher
    environment:
      APP_ENV: "local"
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CHANNEL_NAME: ${TWITCH_CHANNEL_NAME}
      YOUTUBE_AUTH: ${YOUTUBE_AUTH}