version: '3'
services:
  fargaterunner:
    build: ./fargaterunner
    command: bash -c 'go build github.com/user/fargaterunner && zip fargaterunner ./fargaterunner && rm fargaterunner'
    volumes:
      - ./fargaterunner:/go/src/github.com/user/fargaterunner
      
  clipfinder:
    build: ./clipfinder
    command: bash -c "go build github.com/user/clipfinder && zip clipfinder ./clipfinder && cp clipfinder ./bin && rm clipfinder" 
    volumes:
      - ./clipfinder:/go/src/github.com/user/clipfinder

  clipscraper:
    build: ./clipscraper
    command: bash -c "zip -r clipscraper.zip ."
    volumes:
      - ./clipscraper:/app
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
    logging:
      driver: none
