version: '3'
services:
  tf:
    build: ./terraform
    entrypoint: make
    volumes:
      - ./terraform:/terraform
      - ~/.aws:/root/.aws
      - ./clipfinder:/clipfinder
      - ./clipscraper:/clipscraper
      - ./fargaterunner:/fargaterunner
      - ./archiver:/archiver
    environment:
      TF_VAR_TWITCH_CLIENT_ID_DEV: ${TWITCH_CLIENT_ID}
      TF_VAR_TWITCH_CHANNEL_NAME_DEV: ${TWITCH_CHANNEL_NAME}
      TF_VAR_YOUTUBE_AUTH_DEV: ${YOUTUBE_AUTH}