version: 2
jobs:
  test-clipfinder:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pip
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Install docker-compose
          command: pip install docker-compose==1.12.0
      - run:
          name: Run tests
          command: docker-compose -f ./testRunner.yml run clipfinder
  
  build-clipfinder:
    docker:
      - image: lambci/lambda:build-go1.x
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: place clipfinder src in $GOPATH
          command: mkdir -p /go/src/github.com/user/clipfinder && cp -a ~/app/clipfinder/. /go/src/github.com/user/clipfinder/
      - run:
          name: install dependencies
          command: cd /go/src/github.com/user/clipfinder && dep ensure
      - run:
          name: building clipfinder lambda
          command: cd /go/src/github.com/user/clipfinder && go build github.com/user/clipfinder && zip clipfinder ./clipfinder && cp clipfinder.zip ~/app/clipfinder && rm clipfinder

      - save_cache:
          key: clipfinder-lambda-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - clipfinder/clipfinder.zip
  
  check-clipfinder:
    docker:
      - image: lambci/lambda:build-go1.x
    working_directory: ~/app
    steps:
      - restore_cache:
          keys:
            - clipfinder-lambda-cache-{{ .Branch }}-{{ .Revision }}
      - checkout
      - run:
          name: Did the cache work
          command: ls ~/app/clipfinder

  package:
    docker:
      - image: docker:17.10.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install make
          command: apk add --update make
      - run:
          name: Login into docker hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: 
          name: build image
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make build_prod
              else
                make build_dev
              fi
      - run:
          name: push image to docker hub
          command: make hub_push

  deploy:
    docker:
      - image: hashicorp/terraform:0.11.7
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install make
          command: apk add --update make
      - run:
          name: deploy with terraform
          command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  cd terraform && make deploy_prod > /dev/null
                else
                  cd terraform && make deploy_dev > /dev/null
                fi
    

workflows:
  version: 2
  build-package-and-deploy:
    jobs:
       - test-clipfinder

       - build-clipfinder:
          requires: 
            - test-clipfinder
      
       - check-clipfinder:
          requires:
            - build-clipfinder

       - package:
          requires: 
            - build-clipfinder
          filters:
            branches:
              only: 
                - master
                - dev

       - deploy:
          requires: 
            - package
          filters:
            branches:
              only: 
                - master
                - dev
