version: 2
jobs:
  build:
    docker:
      - image: docker:17.12.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pip
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Install docker-compose
          command: pip install docker-compose==1.12.0
      - run:
          name: Run tests
          command: docker-compose -f ./docker-compose.test.yml up --exit-code-from clipstitcher

