version: 2
jobs:
  test:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pip
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Install docker-compose
          command: pip install docker-compose==1.12.0
      - run:
          name: test clipfinder
          command: docker-compose -f ./testRunner.yml run clipfinder
  
  build-go-lambdas:
    docker:
      - image: lambci/lambda:build-go1.x
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: place clipfinder src in $GOPATH
          command: mkdir -p /go/src/github.com/user/clipfinder && cp -a ~/app/clipfinder/. /go/src/github.com/user/clipfinder/
      - run:
          name: install clipfinder dependencies
          command: cd /go/src/github.com/user/clipfinder && dep ensure
      - run:
          name: building clipfinder lambda
          command: cd /go/src/github.com/user/clipfinder && go build github.com/user/clipfinder && zip clipfinder ./clipfinder && cp clipfinder.zip ~/app/clipfinder && rm clipfinder
      - run: 
          name: place fargaterunner src in $GOPATH
          command: mkdir -p /go/src/github.com/user/fargaterunner && cp -a ~/app/fargaterunner/. /go/src/github.com/user/fargaterunner/
      - run:
          name: install fargaterunner dependencies
          command: cd /go/src/github.com/user/fargaterunner && dep ensure
      - run:
          name: building fargaterunner lambda
          command: cd /go/src/github.com/user/fargaterunner && go build github.com/user/fargaterunner && zip fargaterunner ./fargaterunner && cp fargaterunner.zip ~/app/fargaterunner && rm fargaterunner
      - save_cache:
          key: clipfinder-lambda-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - clipfinder/clipfinder.zip
      - save_cache:
          key: fargaterunner-lambda-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - fargaterunner/fargaterunner.zip
    
  build-node-lambdas:
    docker:
      - image: lambci/lambda:build-nodejs8.10
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: install clipscraper dependencies
          command: cd clipscraper && npm install
      - run:
          name: zip clipscraper
          command: cd clipscraper && zip -r clipscraper.zip .
      - save_cache:
          key: clipscraper-lambda-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - clipscraper/clipscraper.zip
  
  build-and-push-clipstitcher-image:
    docker:
      - image: docker:17.10.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install make
          command: apk add --update make
      - run:
          name: Login into docker hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: 
          name: build image
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                make build_prod
              else
                make build_dev
              fi
      - run:
          name: push image to docker hub
          command: make hub_push

  deploy:
    docker:
      - image: hashicorp/terraform:0.11.7
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - clipfinder-lambda-cache-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - fargaterunner-lambda-cache-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - clipscraper-lambda-cache-{{ .Branch }}-{{ .Revision }}
      - run:
          name: install make
          command: apk add --update make
      - run:
          name: deploy with terraform
          command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  cd terraform && make deploy_prod > /dev/null
                else
                  cd terraform && make deploy_dev > /dev/null
                fi
    

workflows:
  version: 2
  build-package-and-deploy:
    jobs:
       - test

       - build-go-lambdas:
          requires: 
            - test
          filters:
            branches:
              only: 
                - master
                - dev
      
       - build-node-lambdas:
          requires: 
            - build-go-lambdas
          filters:
            branches:
              only: 
                - master
                - dev
      
       - build-and-push-clipstitcher-image:
          requires: 
            - build-node-lambdas
          filters:
            branches:
              only: 
                - master
                - dev

       - deploy:
          requires: 
            - build-and-push-clipstitcher-image
          filters:
            branches:
              only: 
                - master
                - dev
